REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (ID_CARGO) values ('AC_ACCOUNT');
Insert into EXPORT_TABLE (ID_CARGO) values ('AC_MGR');
Insert into EXPORT_TABLE (ID_CARGO) values ('AD_ASST');
Insert into EXPORT_TABLE (ID_CARGO) values ('AD_PRES');
Insert into EXPORT_TABLE (ID_CARGO) values ('AD_VP');
Insert into EXPORT_TABLE (ID_CARGO) values ('FI_ACCOUNT');
Insert into EXPORT_TABLE (ID_CARGO) values ('FI_MGR');
Insert into EXPORT_TABLE (ID_CARGO) values ('HR_REP');
Insert into EXPORT_TABLE (ID_CARGO) values ('IT_PROG');
Insert into EXPORT_TABLE (ID_CARGO) values ('MK_MAN');
Insert into EXPORT_TABLE (ID_CARGO) values ('MK_REP');
Insert into EXPORT_TABLE (ID_CARGO) values ('PR_REP');
Insert into EXPORT_TABLE (ID_CARGO) values ('PU_CLERK');
Insert into EXPORT_TABLE (ID_CARGO) values ('PU_MAN');
Insert into EXPORT_TABLE (ID_CARGO) values ('SA_MAN');
Insert into EXPORT_TABLE (ID_CARGO) values ('SA_REP');
Insert into EXPORT_TABLE (ID_CARGO) values ('SH_CLERK');
Insert into EXPORT_TABLE (ID_CARGO) values ('ST_CLERK');
Insert into EXPORT_TABLE (ID_CARGO) values ('ST_MAN');
