REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('AR','Argentina','2');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('AU','Australia','3');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('BE','Belgium','1');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('BR','Brazil','2');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('CA','Canada','2');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('CH','Switzerland','1');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('CN','China','3');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('DE','Germany','1');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('DK','Denmark','1');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('EG','Egypt','4');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('FR','France','1');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('IL','Israel','4');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('IN','India','3');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('IT','Italy','1');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('JP','Japan','3');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('KW','Kuwait','4');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('ML','Malaysia','3');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('MX','Mexico','2');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('NG','Nigeria','4');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('NL','Netherlands','1');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('SG','Singapore','3');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('UK','United Kingdom','1');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('US','United States of America','2');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('ZM','Zambia','4');
Insert into EXPORT_TABLE (ID_PAIS,NOME_PAIS,ID_REGIAO) values ('ZW','Zimbabwe','4');
