-- USER SQL
CREATE USER "TREINAMENTO"  IDENTIFIED BY TREINA
DEFAULT TABLESPACE "USERS";

-- ROLES
GRANT "CONNECT" TO TREINAMENTO WITH ADMIN OPTION;
GRANT "RESOURCE" TO TREINAMENTO WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES
GRANT CREATE ANY SEQUENCE TO TREINAMENTO WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO TREINAMENTO WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO TREINAMENTO WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO TREINAMENTO WITH ADMIN OPTION;
CREATE DIRECTORY DIR_TREINA as 'c:\temp\';
grant read,write on directory DIR_TREINA to public;
grant execute on utl_file to treinamento;